### ISSUE TITLE
Carthage fails to build

### ISSUE THREAD

**Issue by grangej** [RxSwiftCommunity/RxViewModel#46]
I am seeing the following when trying to build with latest Carthage and 4.0 of RxViewModel:

```
Carthage/Checkouts/RxViewModel/Source/RxViewModel.swift:13:8: error: no such module 'RxSwift'
import RxSwift
       ^

** BUILD FAILED **

Cartfile.resolved

github "ReactiveX/RxSwift" "3.5.0"
github "RxSwiftCommunity/RxViewModel" "4.0.0"

```

**Comment by esttorhe** [comment]
Thanks for reporting @grangej.

I'll check this right now and if I can reproduce I'll mark it as confirmed bug and will try to fix it

Thanks

**Comment by esttorhe** [comment]
Just verified this locally.
Will try to fix it during the weekend
