### PR TITLE
🐛 Fixes #46 Carthage build

### LINKED ISSUE #46: Carthage fails to build
I am seeing the following when trying to build with latest Carthage and 4.0 of RxViewModel:

```
Carthage/Checkouts/RxViewModel/Source/RxViewModel.swift:13:8: error: no such module 'RxSwift'
import RxSwift
       ^

** BUILD FAILED **

Cartfile.resolved

github "ReactiveX/RxSwift" "3.5.0"
github "RxSwiftCommunity/RxViewModel" "4.0.0"

```

### PR DESCRIPTION
**Pull request by esttorhe**
Due to a misconfiguration in the project settings when building using `Carthage` was failing because the project was unable to find `RxSwift` dependencies

### CODE REVIEW

File: Supporting Files/RxViewModel.h [hunk 1]
```diff
@@ -6,7 +6,7 @@
 //  Copyright © 2016 Esteban Torres. All rights reserved.
 //
 
-#import <UIKit/UIKit.h>
+#import <Foundation/Foundation.h>
```
Comment (freak4pc) [inline Supporting Files/RxViewModel.h]: What was the reason for changing the import here? Supporting multiple targets? Do we even need any of these imports for this to work? Rest looks great !

Comment (esttorhe) [inline Supporting Files/RxViewModel.h]: Including `UIKit` seemed illogical given that the framework supports all 4 platforms and after the changes I made the `macOS` target wasn't compiling

Comment (freak4pc) [inline Supporting Files/RxViewModel.h]: Yeah makes total sense, I just wondered if we even need the Foundation import there to begin with or it would probably work without?

**Comment by freak4pc** [comment]
Very interesting yet probably not related to this PR, from the tvOS failed CI on Travis

`fatal error: Warning: Recursive call or synchronization error!: file /Users/travis/build/RxSwiftCommunity/RxViewModel/Demo/Pods/RxSwift/RxSwift/Observables/Implementations/AnonymousObservable.swift, line 27` 

Worth looking into at some point @esttorhe

**Comment by freak4pc** [comment]
I don't know the CLANG_WARNIG_INFINITE_RECURSION flag but the fact it was disabled doesn't just silences the warning instead of taking care of the root cause? Or that would be a separate ticket?

**Comment by esttorhe** [comment]
@freak4pc I left the flag as it was originally for now.

As stated on the commit message I need to dig deeper and see how/if `RxSwift` has this flag on because the error is happening deep into `RxSwift` and not on `RxViewModel` level which means that first we would have to patch/fix it there; then turn the flag back on here and update with the latest version.

**Comment by freak4pc** [comment]
@esttorhe AFAIK that recursion error is a warning within RxSwift about code using RxSwift, e.g. it does seem like it is something within RxViewModel but its interesting it only occurred when building on tvOS. If I have a few minutes later this week I'll try building it with the flag and see if I can find anything funky :)

**Comment by esttorhe** [comment]
@freak4pc you might be right :)

I'm going to check this week and see if I can find the root cause of the issue (given that `Travis` is refusing to load that log for me)

Thanks 😄

**Comment by esttorhe** [comment]
Looks like its passing (for now) going to merge and will keep monitoring this issue.

Sadly `TravisCI` refuses to serve me the failed log and thus makes it quite hard for me at the moment to try and fix.

Will keep try locally but i'm going to merge this now

**Comment by freak4pc** [comment]
Sounds good. I'll also try keeping an eye for this issue.
And yeah, Travis is horrid. I still keep hoping everyone will move their OSS projects to Buddybuild 👼
